//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DefSpy {
    
    
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("Microsoft.VisualStudio.Editors.SettingsDesigner.SettingsSingleFileGenerator", "14.0.0.0")]
    internal sealed partial class DefSpy : global::System.Configuration.ApplicationSettingsBase {
        
        private static DefSpy defaultInstance = ((DefSpy)(global::System.Configuration.ApplicationSettingsBase.Synchronized(new DefSpy())));
        
        public static DefSpy Default {
            get {
                return defaultInstance;
            }
        }
        
        [global::System.Configuration.UserScopedSettingAttribute()]
        [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
        [global::System.Configuration.DefaultSettingValueAttribute("")]
        public string ILSpyPath {
            get {
                return ((string)(this["ILSpyPath"]));
            }
            set {
                this["ILSpyPath"] = value;
            }
        }
    }
}
